version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - main
    steps:
      - add_ssh_keys:
          fingerprints:
            - "aa:9d:87:ec:3f:0b:13:4f:6e:d3:55:f7:f0:8f:02:93"
            - "11:12:0c:8a:f5:3a:20:1a:4e:c4:61:d8:2c:28:65:5c"
      - checkout
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: build backend
          command: npm run build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: setup known hosts
          command: ssh-keyscan ${ipAddress} >> ~/.ssh/known_hosts
      - run:
          name: Run deploy scripts
          command: ./scripts/deploy.sh
